# Wedit Makefile for project BigDemo
SRCDIR="c:\4droot\4d-workshop4\installer\common files\goldelox serial\c\samples"
CFLAGS=-I"c:\lcc\include" -I"..\include"  -g2 
CC=$(LCCROOT)\bin\lcc.exe
LINKER=$(LCCROOT)\bin\lcclnk.exe
OBJS=\
	bigdemo.obj \
	"c:\users\public\documents\4d labs\goldelox serial\c\lib\lcc\goldelox_serial_4dlibrary.obj" \

LIBS=gc.lib lfc.lib weditres.lib
EXE="bigdemo.exe"

$(EXE):	$(OBJS) Makefile
	$(LINKER)  -subsystem console -o $(SRCDIR)\"lcc\bigdemo.exe" $(OBJS) $(LIBS)

# Build bigdemo.c
BIGDEMO_C=\
	$(SRCDIR)\bigdemo.h\
	$(SRCDIR)\..\include\Goldelox_const4D.h\
	$(SRCDIR)\..\include\Goldelox_Serial_4DLibrary.h\
	$(SRCDIR)\..\include\Goldelox_Types4D.h\

bigdemo.obj: $(BIGDEMO_C) $(SRCDIR)\"bigdemo.c"
	$(CC) -c $(CFLAGS) $(SRCDIR)\"bigdemo.c"

link:
	$(LINKER)  -subsystem console -o $(SRCDIR)\"lcc\bigdemo.exe" $(OBJS) $(LIBS)

clean:
	del $(OBJS) bigdemo.exe
