#include <windows.h>

#include "..\include\Goldelox_Types4D.h"			// defines data types used by the 4D Routines
#include "..\include\Goldelox_const4DSerial.h"	// function call index definitions, generated by build of serial
#include "..\include\Goldelox_const4D.h"			// defines for 4dgl constants, generated by conversion of 4DGL constants to target language

#define   Err4D_OK      0
#define   Err4D_Timeout 1
#define   Err4D_NAK		2 // other than ACK received


// 4D Global variables
HANDLE ComHandle4D ;  		// comp port handle, used by Intrinsic routines
int Error4D ;  				// Error indicator,  used and set by Intrinsic routines
unsigned char Error4D_Inv ;	// Error byte returned from com port, onl set if error = Err_Invalid
//int Error_Abort4D ;  		// if true routines will abort when detecting an error
int TimeLimit4D ;			// time limit in ms for total serial command duration, 2000 (2 seconds) should be adequate for most commands
                            // assuming a reasonable baud rate AND low latency AND 0 for the Serial Delay Parameter
                            // temporary increase might be required for very long (bitmap write, large image file opens)
                            // or indeterminate (eg file_exec, file_run, file_callFunction)  commands
int(*Callback4D) (int, unsigned char) ;

#include "..\include\Goldelox_Intrinsic4DRoutines.inc"
#include "..\include\Goldelox_Compound4DRoutines.inc"

int OpenComm(char *comport, int newrate)
{
	COMMTIMEOUTS com1time ;
	DWORD        errs ;
	unsigned char port[10] ;

	strcpy(port, "\\\\.\\") ;
	strcat(port, comport) ;
	ComHandle4D = CreateFile(port,
	                         GENERIC_READ + GENERIC_WRITE, 0, NULL,
	               			 OPEN_EXISTING, 0, 0) ;
	if (ComHandle4D == INVALID_HANDLE_VALUE)
	{
		return GetLastError() ;
	}

	GetCommTimeouts(ComHandle4D, &com1time) ;
	com1time.ReadIntervalTimeout = MAXDWORD ;
	com1time.ReadTotalTimeoutMultiplier = 0; //give chance to respond
	com1time.ReadTotalTimeoutConstant   = 10 ; //update 100x a second
	SetCommTimeouts(ComHandle4D,&com1time) ;

	SetBaudrate(newrate) ;

	errs = 0xffff ;
	ClearCommError(ComHandle4D,&errs,NULL) ;

	PurgeComm(ComHandle4D,PURGE_TXABORT+PURGE_RXABORT+PURGE_TXCLEAR+PURGE_RXCLEAR) ;
	return 0 ;
}

